services:
  gamerepository:
    class: \Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - JoshWillisRockPaperScissorsLizardSpockBundle\Entity\Game